MovieApp.WebMVC/Controllers/CastController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieApp.WebMVC.Controllers
{
    public class CastController : Controller
    {
        private readonly ICastService _castService;
        private readonly ICastServiceAsync _castServiceAsync;

        public CastController(ICastService castService, ICastServiceAsync castServiceAsync)
        {
            _castService = castService;
            _castServiceAsync = castServiceAsync;
        }

        
        public async Task<IActionResult> Details(int id)
        {
            var CastDetails = await _castServiceAsync.GetByIdAsync(id);
            return View(CastDetails);
        }
    }
}

MovieApp.WebMVC/Controllers/GenreController.cs
using ApplicationCore.Contracts.Repositories;
using ApplicationCore.Contracts.Services;
using ApplicationCore.Entities;
using Microsoft.AspNetCore.Mvc;

namespace MovieApp.WebMVC.Controllers
{
    public class GenreController : Controller
    {
        private readonly IGenreService _genreService;
        private readonly IGenreServiceAsync _genreServiceAsync;
        public GenreController(IGenreService genreService, IGenreServiceAsync genreServiceAsync)
        {
            _genreService = genreService;
            _genreServiceAsync = genreServiceAsync;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _genreServiceAsync.GetAllGenreAsync();
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Genre genre)
        {
            if(ModelState.IsValid)
            {
                await _genreServiceAsync.AddGenreAsync(genre);
                return RedirectToAction("Index");
            }
            return View(genre);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _genreServiceAsync.GetGerneByIdAsync(id);
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Genre genre)
        {
            if(ModelState.IsValid)
            {
                await _genreServiceAsync.UpdateGenreAsync(genre, genre.Id);
                return RedirectToAction("Index");
            }
            return View(genre);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _genreServiceAsync.DeleteGenreAsync(id);
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Genre genre)
        {
            await _genreServiceAsync.DeleteGenreAsync(genre.Id);
            return RedirectToAction("Index");
        }   

        
    }
}

MovieApp.WebMVC/Controllers/MoviesController.cs
using ApplicationCore.Contracts.Repositories;
using ApplicationCore.Contracts.Services;
using ApplicationCore.Entities;
using Microsoft.AspNetCore.Mvc;
using MovieApp.WebMVC.Models;

namespace MovieApp.WebMVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IGenreService _genreService;
        private readonly IMovieServiceAsync _movieServiceAsync;
        private readonly IGenreServiceAsync _genreServiceAsync;
        private readonly IMovieRepositoryAsync _movieRepository;
        public MoviesController(IMovieService movieService, IGenreService genreService, IMovieServiceAsync movieServiceAsync, IGenreServiceAsync genreServiceAsync, IMovieRepositoryAsync movieRepositoryAsync)
        {
            _movieService = movieService;
            _genreService = genreService;
            _movieServiceAsync = movieServiceAsync;
            _genreServiceAsync = genreServiceAsync;
            _movieRepository = movieRepositoryAsync;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Details()
        {
            ViewBag.GenreNames = await _movieServiceAsync.GetGenreAsync(1);
            ViewBag.Trailers = await _movieServiceAsync.GetTrailersByIdAsync(1);
            ViewBag.CastWithCharacter = await _movieServiceAsync.GetCastsAsync(1);
            //ViewBag.Rating = _movieService.GetRate(1);
            var movie = await _movieServiceAsync.GetMovieDetailsAsync(1);
            return View(movie);
        }

        [HttpGet]
        public async Task<IActionResult> Review(int id)
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Review(Review review)
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Buy()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Genre(string genreName, int pageNumber = 1, int pageSize = 30)
        {
            try
            {
                int id = await _genreServiceAsync.GetIdByNameAsync(genreName);
                var moviesQuery = await MoviesByGenreAsync(id, pageSize, pageNumber);
                var movies = moviesQuery
                    .Skip((pageNumber - 1) * pageSize)
                    .Take(pageSize)
                    .ToList();
                var totalMovies = moviesQuery.Count();

                var result = new MoviesByGenreModel
                {
                    Movies = movies,
                    CurrentPage = pageNumber,
                    TotalPages = (int)Math.Ceiling(totalMovies / (double)pageSize) < 1 ? 1 : (int)Math.Ceiling(totalMovies / (double)pageSize),
                    Genre = genreName
                };


                return View(result);


            } 
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View("Error");
            }
        }

        public async Task<IEnumerable<Movie>> MoviesByGenreAsync(int id, int pageSize = 30, int pageNumber = 1)
        {
            var genre = await _genreServiceAsync.GetGerneByIdAsync(id);
            return await _movieRepository.GetMoviesByGenreAsync(genre, pageNumber, pageSize);

        }
    }
}

MovieApp.WebMVC/Views/Movies/Details.cshtml
@model Movie;

@{
    ViewData["Title"] = "Movie Details";
}

<div class="container">
    <div class="row" style="background-image: url(@Model.BackdropUrl)">
        <div class="col-4">
            <div class="card">
                <img src="@Model.PosterUrl" alt="..." />
            </div>
        </div>
        <div class="col text-white">
            <h4>@Model.Title</h4>
            <p>@Model.Tagline</p>
            <h6>@Model.RunTime m | @($"{Model.ReleaseDate:yyyy}") 
                @foreach (var name in ViewBag.GenreNames)
                {
                    <span class="badge bg-secondary">@name</span>
                }
            </h6>
            <h6><span class="badge bg-success">Rating</span></h6>
            <h6>@Model.Overview</h6>
        </div>
        <div class="col">
            <div class="row">
                <button type="button" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#ReviewModal">REVIEW</button>
            </div>
            <div class="row">
                <button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#BuyModal">Buy @Model.Price</button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <h5>MOVIE FACTS</h5>
            <h6>Release Date <span class="badge bg-secondary">@Model.ReleaseDate</span></h6>
            <hr />
            <h6>RunTime <span class="badge bg-secondary">@Model.RunTime m</span></h6>
            <hr />
            <h6>Budget <span class="badge bg-secondary">$@Model.Budget</span></h6>
            <hr />
            <h5>TRAILERS</h5>
            <ul class="list-group list-group-flush">
                @foreach (var trailer in ViewBag.Trailers)
                {
                    <li class="list-group-item" style="background-color: #edede9;">
                        <div style="display: flex;">
                            <i class="fab fa-youtube" style="width: 50px;"></i>
                            <a href="@trailer.TrailerUrl" style="text-decoration: none;"><p>@trailer.Name</p></a>
                        </div>
                    </li>
                }
            </ul>
        </div>
        <div class="col">
            <h5>CAST</h5>
            <ul class="list-group list-group-flush">
                @foreach (var item in ViewBag.CastWithCharacter)
                {
                    <li class="list-group-item">
                        <div class='actor' style="display:flex;  align-items: center;">
                            <a asp-controller="Cast" asp-action="Detail" asp-route-id="@item.Cast.Id">
                                <img src="@item.Cast.ProfilePath" style=" width: 60px; height:60px; border-radius:30px; margin-right: 80px;" onclick="" />
                            </a>
                            <div style="width: 300px;"><p>@item.Cast.Name</p></div>
                            <div><p>@item.Character</p></div>

                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="ReviewModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Review</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to review?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" asp-action="Review" asp-controller="Movie" asp-route-id="@Model.Id">Continue</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="BuyModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Buy</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to buy this movie?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" asp-action="Buy" asp-controller="Movie" asp-route-id="@Model.Id">Purchase @Model.Price</button>
            </div>
        </div>
    </div>
</div>

MovieApp.WebMVC/Views/Movies/Genre.cshtml
@model MoviesByGenreModel;

@{
    ViewData["Title"] = "Movies by Genre";
}

@if (Model == null)
{
    <p>Sorry, there was an error loading movies. Please try again later.</p>
}

<div class="movies-by-genre">

    <div class="container-fluid">
        <div class="row">
            @foreach (var item in Model.Movies)
            {
                <partial name="_MovieCard" model="item" />
            }
        </div>
    </div>

    <nav style="margin-top: 30px;" aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-genreName="@Model.Genre" asp-route-pageNumber="1" aria-label="First">
                    <span aria-hidden="true">First Page</span>
                </a>
            </li>


            <li class="page-item">
                @if (Model.CurrentPage > 1)
                {
                    <a class="page-link"
                       asp-controller="Movies" asp-action="Genre" asp-route-genreName="@Model.Genre" asp-route-pageNumber="@(Model.CurrentPage-1)" aria-label="Prev">
                        <span aria-hidden="true">Prev</span>
                    </a>
                }
            </li>


            @if (Model.CurrentPage >= 4)
            {
                <li class="page-item"><a class="page-link">....</a></li>

            }
            @if (Model.CurrentPage >= 3)
            {
                <li class="page-item "><a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-genreName="@Model.Genre" asp-route-pageNumber="@(Model.CurrentPage-2)">@(Model.CurrentPage - 2)</a></li>
            }
            @if (Model.CurrentPage >= 2)
            {
                <li class="page-item "><a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-genreName="@Model.Genre" asp-route-pageNumber="@(Model.CurrentPage-1)"> @(Model.CurrentPage - 1)</a></li>
            }
            <li class="page-item active" aria-current="page"><a class="page-link  " asp-controller="Movie" asp-action="Genre" asp-route-genreName="@Model.Genre" asp-route-pageNumber="@Model.CurrentPage">@Model.CurrentPage</a></li>
            @if (Model.CurrentPage < Model.TotalPages - 2)
            {
                <li class="page-item "><a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-genreName="@Model.Genre" asp-route-pageNumber="@(Model.CurrentPage+1)">@(Model.CurrentPage + 1)</a></li>
            }

            @if (Model.CurrentPage < Model.TotalPages - 3)
            {
                <li class="page-item"><a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-genreName="@Model.Genre" asp-route-pageNumber="@(Model.CurrentPage+2)">@(Model.CurrentPage + 2)</a></li>

            }

            @if (Model.CurrentPage > 0 && Model.CurrentPage < Model.TotalPages - 3)
            {
                <li class="page-item"><a class="page-link">....</a></li>

            }


            @if (Model.CurrentPage < Model.TotalPages - 3)
            {
                <li class="page-item"><a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-genreName="@Model.Genre" asp-route-pageNumber="@(Model.TotalPages)">@(Model.TotalPages)</a></li>
            }
            <li class="page-item">
                @if (Model.CurrentPage < Model.TotalPages)
                {
                    <a class="page-link"
                       asp-controller="Movies" asp-action="Genre" asp-route-genreName="@Model.Genre" asp-route-pageNumber="@(Model.CurrentPage+1)" aria-label="Next">
                        <span aria-hidden="true">Next</span>
                    </a>
                }



            </li>

            <li class="page-item">
                <a class="page-link" asp-controller="Movies" asp-action="Genre" asp-route-genreName="@Model.Genre" asp-route-pageNumber="@(Model.TotalPages)" aria-label="End">
                    <span aria-hidden="true">End Page</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

MovieApp.WebMVC/Views/Movies/Index.cshtml
@{
    ViewData["Title"] = "Movie page";
}
<h1>@ViewData["Title"]</h1>

MovieApp.WebMVC/Views/Movies/Review.cshtml
@model Review;

@{
    ViewData["Title"] = "Review";
}
<h1>@ViewData["Title"]</h1>

<form asp-action="Review" method="post" asp-controller="Movie">
    <div class="container">
        <div class="my-3">
            <select class="form-select" aria-label="Default select example" asp-for="Rating">
                <option selected>Rating</option>
                @for (int i = 1; i <= 10; i++)
                {
                    <option value="@i">@i</option>
                }
            </select>
        </div>
        <div class="my-3">
            <label for="ReviewText">Reviews</label>
            <input type="text" asp-for="ReviewText" class="form-control" />
        </div>
        <button class="btn btn-submit">Submit</button>
    </div>
</form>