MovieApp.WebMVC/ViewComponents/GenreListViewComponent.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieApp.WebMVC.ViewComponents
{
    public class GenreListViewComponent : ViewComponent
    {
        private readonly IGenreServiceAsync _genreService;
        public GenreListViewComponent(IGenreServiceAsync genreService)
        {
            _genreService = genreService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var genres = await _genreService.GetAllGenreAsync();
            return View(genres);
        }
    }
}

MovieApp.WebMVC/Views/Shared/_Header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <div>
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Movie Shop🎞️</a>

                <div class="btn-group">
                    <button class="btn btn-lg dropdown-toggle bg-dark border-0 text-white" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        GENRES
                    </button>
                    <ul class="dropdown-menu text-white">
                        @await Component.InvokeAsync("GenreList")
                    </ul>
                </div>
            </div>
            <div>
                <button class="btn btn-lg bg-dark text-white border-white" type="button" aria-expanded="false">Login</button>
                <button class="btn btn-lg bg-dark text-white border-white" type="button" aria-expanded="false">Register</button>
            </div>
        </div>
    </nav>
</header>

MovieApp.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieApp.WebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <partial name="_Header" />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieApp.WebMVC/Views/Shared/_MovieCard.cshtml
@model Movie;

<div class="col-lg-2">
    <div class="card">
        <a href="@Model.ImdbUrl">
            <img src="@Model.PosterUrl" class="card-img" alt="..." />
        </a>
    </div>
</div>